import time, os

def storyStart():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("You found a mysterious dungeon in the woods...")
    time.sleep(1)
    print("Curious about what's inside, you decide to enter it without hesitation.")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage1():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("You entered a rather dark hall with many torches inside.")
    time.sleep(1)
    print("And then suddenly a figure appears and getting closer to you...")
    time.sleep(1)
    print("These things doesn't seem so friendly, you get ready your weapons and prepare to fight them.")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage1():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("You delve deeper into the dungeon...")
    time.sleep(1)
    print("The interiors seem to look all the same, but you started to see the remains of dead adventurers in the way.")
    time.sleep(1)
    print("You heard a rattling noise, and when you look back, you see those lifeless bones get up move like a skeleteon...")
    time.sleep(1)
    print("Sensing danger coming, you get ready for battle...")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage3():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("You enter a new area, where the interiors started to change.")
    time.sleep(1)
    print("It's much brighter than the last hall, but now you can see clearly the monsters that are lurking around.")
    time.sleep(1)
    print("And what do you expect? They already saw you when you entered. They started to stand and take their weapons.")
    time.sleep(1)
    print("They started to walk slowly, and then run towards you with bad intentions.")
    time.sleep(1)
    print("Get ready to fight!")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage4():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("The atmosphere started to change. You don't see those green goblins anymore in here.")
    time.sleep(1)
    print("You only see lifeless skeletons wandering around.")
    time.sleep(1)
    print("But then, you saw a figure wearing coat and visible fangs out of his mouth.")
    time.sleep(1)
    print("The figure suddenly reappears behind you, and when you look back, blood drips from the fangs.")
    time.sleep(1)
    print("Looks like a vampire. This is not something that can be taken lightly.")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage5():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("The area is so big, and you continue to search the right way.")
    time.sleep(1)
    print("Every small rooms that you enter, resides the spooky scary skeletons and bloodsucking vampires waiting to attack.")
    time.sleep(1)
    print("Chills run down your spine. Something doesn't seem right... You feel like someone is watching you...")
    time.sleep(1)
    print("Regardless, you still have some business to take care.")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage6():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("You found an opening to a weird sort of cave. You entered the gloomy looking cave.")
    time.sleep(1)
    print("Turns out it's an entrance to a sort of underground dark castle. You decided to go to the main gate.")
    time.sleep(1)
    print("Bats fly over your head as you open the main gate and enter the main hall.")
    time.sleep(1)
    print("A red monster descends in front of you. It's long horns glow dim red and wings move as it walks towards you.")
    time.sleep(1)
    print("The red demon says something that you couldn't catch, or rather you don't know the language he's saying.")
    time.sleep(1)
    print("Suddenly, it jumps back and roars loudly. Then, other demons and vampires started to appear.")
    time.sleep(1)
    print("This is bad news. You need to survive this...")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage7():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================")
    print("You found some ominous aura ")