import time, os

def storyStart():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("You found a mysterious dungeon in the woods...\n")
    time.sleep(1)
    print("Curious about what's inside, you decide to enter it without hesitation.\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage1():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("You entered a rather dark hall with many torches inside.\n")
    time.sleep(1)
    print("And then suddenly a figure appears and getting closer to you...\n")
    time.sleep(1)
    print("These things doesn't seem so friendly, you get ready your weapons and prepare to fight them.\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage2():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("You delve deeper into the dungeon...\n")
    time.sleep(1)
    print("The interiors seem to look all the same, but you started to see the remains of dead adventurers in the way.\n")
    time.sleep(1)
    print("You heard a rattling noise, and when you look back, you see those lifeless bones get up move like a skeleteon...\n")
    time.sleep(1)
    print("Sensing danger coming, you get ready for battle...\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage3():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("You enter a new area, where the interiors started to change.\n")
    time.sleep(1)
    print("It's much brighter than the last hall, but now you can see clearly the monsters that are lurking around.\n")
    time.sleep(1)
    print("And what do you expect? They already saw you when you entered. They started to stand and take their weapons.\n")
    time.sleep(1)
    print("They started to walk slowly, and then run towards you with bad intentions.\n")
    time.sleep(1)
    print("Get ready to fight!")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage4():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("The atmosphere started to change. You don't see those green goblins anymore in here.\n")
    time.sleep(1)
    print("You only see lifeless skeletons wandering around.\n")
    time.sleep(1)
    print("But then, you saw a figure wearing coat and visible fangs out of his mouth.\n")
    time.sleep(1)
    print("The figure suddenly reappears behind you, and when you look back, blood drips from the fangs.\n")
    time.sleep(1)
    print("Looks like a vampire. This is not something that can be taken lightly.\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage5():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("The area is so big, and you continue to search the right way.\n")
    time.sleep(1)
    print("Every small rooms that you enter, resides the spooky scary skeletons and bloodsucking vampires waiting to attack.\n")
    time.sleep(1)
    print("Chills run down your spine. Something doesn't seem right... You feel like someone is watching you...\n")
    time.sleep(1)
    print("Regardless, you still have some business to take care.\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage6():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("You found an opening to a weird sort of cave. You entered the gloomy looking cave.\n")
    time.sleep(1)
    print("Turns out it's an entrance to a sort of underground dark castle. You decided to go to the main gate.\n")
    time.sleep(1)
    print("Bats fly over your head as you open the main gate and enter the main hall.\n")
    time.sleep(1)
    print("A red monster descends in front of you. It's long horns glow dim red and wings move as it walks towards you.\n")
    time.sleep(1)
    print("The red demon says something that you couldn't catch, or rather you don't know the language he's saying.\n")
    time.sleep(1)
    print("Suddenly, it jumps back and roars loudly. Then, other demons and vampires started to appear.\n")
    time.sleep(1)
    print("This is bad news. You need to survive this...\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyStage7():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("You sense some ominous aura coming from one of the gates in the castle...\n")
    time.sleep(1)
    print("You decided to open the gate, and the you enter a big, long hall with a crimson throne at the end of it.\n")
    time.sleep(1)
    print("You see a figure sitting in the throne. The moment you decided to take the first step towards it, two glowing points started to appear in it's head.\n")
    time.sleep(1)
    print("'Welcome human! Are you here to die, like all previous ones that come here did?'\n")
    time.sleep(1)
    print("You decided to not answer him and walk towards the throne...\n")
    time.sleep(1)
    print("'Not answering huh?' The figure then disappears immediately as you stopped walking.\n")
    time.sleep(1)
    print("You see a big shadow from behind you, and when you look back, you see a giant figure with dark aura and intimidating presence stood in front of you...\n")
    time.sleep(1)
    print("'Weakling! Let's see how fragile you are!' It seems this is the 'final boss' of this castle\n")
    time.sleep(1)
    input("\nPress enter to continue>>")

def storyEnd():
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("'You... who are you.. How can a human be this strong...\n")
    time.sleep(1)
    print("You ignored his question as you are about to finish him in his last moments...\n")
    time.sleep(1)
    print("'Fool! I am an immortal being, even if I am killed now, I'll reincarnate and do this all over again!'\n")
    time.sleep(1)
    print("'Whatever.', you said as you finish the so called 'Demon King'\n")
    time.sleep(1)
    print("The demon king dies, and you leave the castle altogether with the loots you find.\n")
    time.sleep(3)
    input("\nPress enter to continue>>")
    os.system('cls' if os.name == 'nt' else 'clear')
    print("=============== STORY ================\n")
    print("Days later, you heard about the dungeon you've visited that monsters started to roam around again in there.\n")
    time.sleep(1)
    print("It seems the king is back. What to do now is up to you...\n")
    time.sleep(1)
    input("\nPress enter to continue>>")